#!/bin/sh
# Inspect the user's shell rc files so the install-mfw skill can decide whether
# it may edit them directly, or whether they are *managed* (symlinked into nix /
# home-manager / chezmoi / GNU stow / a dotfiles git repo) and mfw's source line
# must instead go into the user's source-of-truth.
#
# WHY THIS MATTERS: `mfw fixup` writes its source line with an atomic
# rename(tmp, rc). On a symlinked rc that REPLACES the symlink with a regular
# file — clobbering a home-manager/nix-managed rc. So a managed rc must never be
# edited in place.
#
# Output is a parseable report (key=value lines under a `--- <path>` header),
# then a CANDIDATES section of source-of-truth files that exist. Parse it; do
# not show it verbatim to the user.
set -u

home="${HOME:-$(cd ~ 2>/dev/null && pwd)}"

resolve() {
	# Follow the whole symlink chain when we can; fall back to one hop.
	if command -v realpath >/dev/null 2>&1; then
		realpath "$1" 2>/dev/null && return 0
	fi
	readlink "$1" 2>/dev/null
}

classify() {
	# $1 = resolved/target path -> a coarse guess at who manages it.
	case "$1" in
	/nix/store/* | */nix/store/*) echo nix ;;
	"$home/.local/share/chezmoi"/*) echo chezmoi ;;
	*)
		d=$(dirname "$1" 2>/dev/null || echo /)
		if command -v git >/dev/null 2>&1 && git -C "$d" rev-parse --show-toplevel >/dev/null 2>&1; then
			echo git-dotfiles
		else
			echo unknown
		fi
		;;
	esac
}

# $SHELL's rc is the one that actually matters for the user's login shell.
login_shell=$(basename "${SHELL:-}" 2>/dev/null)
echo "login_shell=$login_shell"

for f in \
	"$home/.zshrc" \
	"$home/.bashrc" \
	"$home/.bash_profile" \
	"$home/.profile" \
	"$home/.config/fish/config.fish"; do
	echo "--- $f"
	if [ -L "$f" ]; then
		tgt=$(readlink "$f")
		res=$(resolve "$f")
		echo "exists=yes"
		echo "symlink=yes"
		echo "link_target=$tgt"
		echo "resolved=${res:-$tgt}"
		echo "class=$(classify "${res:-$tgt}")"
		if [ -w "${res:-$tgt}" ] 2>/dev/null; then echo "writable=yes"; else echo "writable=no"; fi
	elif [ -e "$f" ]; then
		echo "exists=yes"
		echo "symlink=no"
		if [ -w "$f" ]; then echo "writable=yes"; else echo "writable=no"; fi
		# home-manager / nix can also write a *real* file with a generated header.
		if head -n 5 "$f" 2>/dev/null | grep -qiE 'Generated by (Home Manager|Nix)|nix-managed'; then
			echo "class=nix-generated"
		else
			echo "class=plain"
		fi
	else
		echo "exists=no"
	fi
done

echo "--- CANDIDATES"
for c in \
	"$home/.config/home-manager/home.nix" \
	"$home/.config/home-manager/flake.nix" \
	"$home/.config/nixpkgs/home.nix" \
	"$home/.config/nixpkgs/config.nix" \
	"$home/.config/nix-darwin/flake.nix" \
	"$home/.nixpkgs/darwin-configuration.nix" \
	"/etc/nixos/configuration.nix" \
	"/etc/nixos/flake.nix" \
	"/etc/nix-darwin/configuration.nix" \
	"$home/.local/share/chezmoi" \
	"$home/dotfiles" \
	"$home/.dotfiles"; do
	[ -e "$c" ] && echo "candidate=$c"
done
true
